apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shop.fullname" . }}-config
  labels:
    {{- include "shop.labels" . | nindent 4 }}
data:
  FLASK_APP: {{ .Values.config.FLASK_APP | quote }}
  FLASK_ENV: {{ .Values.api.env.FLASK_ENV | quote }}
  SECURITY_ARTIFACTS_DIR: {{ .Values.api.env.SECURITY_ARTIFACTS_DIR | quote }}
