{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shop.fullname" . }}-web
  labels:
    {{- include "shop.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "shop.web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shop.web.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/api-upstream: {{ .Values.web.apiUpstream | sha256sum }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: API_UPSTREAM
              value: {{ .Values.web.apiUpstream | quote }}
            - name: NGINX_ENVSUBST_FILTER
              value: API_UPSTREAM
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-conf-d
              mountPath: /etc/nginx/conf.d
            - name: nginx-logs
              mountPath: /var/log/nginx
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.web.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.web.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.web.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.web.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.web.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.web.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        # conf.d is written by envsubst entrypoint from templates/
        - name: nginx-conf-d
          emptyDir: {}
        - name: nginx-logs
          emptyDir: {}
{{- end }}
